apiVersion: v1
kind: PersistentVolume
metadata:
  name: dataset-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: "/tmp/nfs/raw_datasets"
    server: 10.2.12.7
