apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-role-kubeflow-test
  namespace: kubeflow
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - "*"
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-kubeflow-test
  namespace: kubeflow
subjects:
- kind: ServiceAccount
  name: spark-operator-spark-kubeflow-test
  namespace: kubeflow
roleRef:
  kind: Role
  name: spark-operator-spark
  apiGroup: rbac.authorization.k8s.io
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-operator-spark-kubeflow-test
  namespace: kubeflow