apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: processed-datasets-pvc
  namespace: spark-operator
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: processed-datasets-pv
