apiVersion: v1
kind: PersistentVolume
metadata:
  name: processed-datasets-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: "/tmp/nfs/processed_datasets"
    server: 10.2.12.7
