apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: my-pvc
  namespace: spark-operator
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
